pipeline{
    agent any
   
    tools { 
        maven 'maven'
        jdk 'jdk'
    }
        stages{
            stage('Git-Checkout')
            {
                steps{
                     git 'https://github.com/sravanin15/PipelineSonar.git'
                }
            }
             stage('Clean')
        {
            steps{
                bat 'mvn -f PipelineSonarqube clean'
            }
        }
             stage('Validate')
        {
            steps{
                bat 'mvn -f PipelineSonarqube validate'
            }
        }
        stage('Compile')
        {
            steps{
                bat 'mvn -f  PipelineSonarqube compile'
            }
        }
        stage('sonar analysis'){
            steps{
                withSonarQubeEnv('sonarserver'){
                    withMaven(maven:'maven'){
                        bat 'mvn -f  PipelineSonarqube sonar:sonar'
                    }
                }
            }

        }

        stage('Test')
        {
            steps{
                bat 'mvn -f  PipelineSonarqube test'
            }
        }
        stage('Package')
        {
            steps{
                bat 'mvn -f  PipelineSonarqube package'
            }
        }
        stage('Verify')
        {
            steps{
                bat 'mvn -f PipelineSonarqube verify'
            }
        }
        stage('Install')
        {
            steps{
                bat 'mvn -f PipelineSonarqube install'
            }
        }
            
            
           
        }
}
